name: Build and push Docker image

on:
  workflow_dispatch:
  schedule:
    - cron: "23 3 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - id: base-image-update-check
        name: Check for updates to FileBot base image
        uses: lucacome/docker-image-update-checker@v2
        with:
          base-image: rednoah/filebot:watcher
          image: ghcr.io/blolol/filebot-watcher:latest
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.7.1
        if: steps.base-image-update-check.outputs.needs-updating == 'true'
      - name: Log into GitHub Container Registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        if: steps.base-image-update-check.outputs.needs-updating == 'true'
      - name: Build and push Docker image
        uses: docker/build-push-action@v6.9.0
        with:
          file: Dockerfile.watcher
          push: true
          tags: blolol/filebot-watcher:latest
        if: steps.base-image-update-check.outputs.needs-updating == 'true'
