name: Build and push Docker image

on:
  workflow_dispatch:
  schedule:
    - cron: "23 3 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU for multi-platform builds
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log into GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - id: base-image-update-check
        name: Check for updates to FileBot base image
        uses: lucacome/docker-image-update-checker@v2
        with:
          base-image: rednoah/filebot:watcher
          image: ghcr.io/blolol/filebot-watcher:latest
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          file: Dockerfile.watcher
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/blolol/filebot-watcher:latest
        if: steps.base-image-update-check.outputs.needs-updating == 'true' || github.event_name == 'workflow_dispatch'
